export type Row = { line: number; date: string; iso: string | null; description: string; amount: number; type: string; transactionId?: string | null };
export type Receipt = { month: string; amount: number; date?: string; mxnAmount?: number; cardLast4?: string; source?: 'bank' | 'document' | 'user' };
export type Source = { name: string; text: string };
export type Report = { isAdjustment?: boolean; id?: string; currency?: 'MXN' | 'USD'; documentDate?: string; cardLast4?: string; receipt?: Receipt; sales?: number; salesBase?: number; salesFee?: number; salesSource?: Source; commissionSource?: Source & { file?: string }; earningsSource?: Source; earnings?: Report; file?: string; kind?: 'earnings' | 'apple' | 'stripe' | 'mercado' | 'cursor' | 'facebook' | 'chatgpt' | 'google' | 'supabase' | 'cloud'; countries?: { code: string; charges: number; gross: number; refunds: number; net: number }[]; name: string; period: string; text: string; rows: Row[]; totals: Record<string, number>; difference: number; importedAt: string; hasOperations: boolean };
export type Workspace = { reports: Report[]; links: Record<string, string>; notes: Record<string, string>; bank: Record<string, string> };
export type Payout = Row & { id: string; report: Report };
export function money(cents: number): string;
export function validateReceipt(receipt: unknown): Receipt;
export function mexicoVat(report: Report): { gross: number; base: number; vat: number } | null;
export function escapeHtml(value: unknown): string;
export function parseAmount(value: string): number;
export function dateISO(value: string): string | null;
export function parseReport(text: string, name: string): Report;
export function appleSales(text: string, name: string): { period: string; customer: number; base: number; fee?: number; earned?: number };
export function payoutRows(reports: Report[], month: string): Payout[];
export function csv(rows: Record<string, unknown>[]): string;
export function validDate(value: unknown): boolean;
export function roundSigned(value: number): number;
export function reportKey(report: Report): string;
export function suggestedAmount(report: Report): number;
export function paymentAmount(report: Report): number | null;
export function upsertReport(reports: Report[], report: Report, month?: string): Report[];
export function attachPlayEarnings(report: Report, source: Source): Report;
export function attachAppleSales(report: Report, source: Source): Report;
export function incomeFigures(report: Report): { sales: number | null; base: number | null; salesVat: number | null; fee: number | null; feeVat: number | null; preliminaryVat: number | null };

export function appleCommissionInvoice(text: string, name: string): { period: string; earned: number; fee: number; feeVat: number; invoiceTotal: number };
export function attachAppleCommission(report: Report, source: Source & { file?: string }): Report;

export function missingAppleFiles(report?: Report): string[];
